var AsphyxiaPath = "C:\\Users\\kryvas\\Downloads\\asphyxia-core-win-x64\\asphyxia.exe"
var SDVX3Path = "C:\\UI\\arcade-machine\\ui\\spice.exe"
var SDVX4Path = ""
var SDVX5Path = ""
var browser = "brave.exe"