var AsphyxiaPath = "C:\\Users\\kryvas\\Downloads\\asphyxia-core-win-x64\\asphyxia.exe"
var SDVX3Path = "C:\\Users\\kryvas\\Downloads\\sdvx\\Sound voltex iii gravity wars\\spice.exe"
var SDVX4Path = ""
var SDVX5Path = ""
var browser = "brave.exe"